version: "3.7"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node_client
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /sample-graphql
    tty: true
    stdin_open: true
