version: "3.7"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node_client
    command: npm run dev
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - type: bind
        source: .
        target: /sample-graphql
    tty: true
    stdin_open: true

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data:
